# Title Cell - Update

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

from pandas_datareader import wb
from sklearn.preprocessing import PolynomialFeatures

warnings.filterwarnings("ignore")

## Load Data

In [2]:
code = 'EN.CO2.BLDG.ZS'
# CO2 emissions from residential buildings and from commercial and from public services (% of total fuel combustion)

In [3]:
regions = ['BRA',  'IND', 'CHN', 'ZAF', 'USA', 'GBR', 'WLD', 'EUU']

In [4]:
pd.set_option("display.max_rows", None)

In [5]:
try:
    df_indicator = wb.download(
        country=regions,
        indicator=code,
        start=1971, 
        end=2014
    )
except: 
    df_indicator = pd.read_excel("indicator_world_bank_original.xlsx", index_col = [0,1])
    # If the connection to worldbank does not work, then you will load the data from this file. 
    # make sure you have this excel file i.e. indicator_world_bank_original.xlsx in the python working directory.
    # you can find this file if you search in the data in this course.
    # Also: even if the connection to worldbank works, you can still use this excel file if you want to 
    # use the exact same data as the ones that are in the videos of this course. Because otherwise, 
    # worldbank's data may change from time to time. Eg WorldBank may add more data or change some values of 
    # existing data.

df_indicator

EN.CO2.BLDG.ZS
country        year                
Brazil         2014        4.289736
               2013        4.508896
               2012        4.746116
               2011        5.159270
               2010        5.346396
               2009        6.042296
               2008        5.728822
               2007        6.021721
               2006        6.104512
               2005        6.177134
               2004        6.369242
               2003        6.573187
               2002        7.184062
               2001        7.230568
               2000        7.320995
               1999        7.695609
               1998        7.568926
               1997        7.635852
               1996        8.034153
               1995        8.629018
               1994        8.940114
               1993        8.748152
               1992        8.814062
               1991        8.735680
               1990        8.938942
               1989        8.538303
               1988        8.511921
               1987        7.800390
               1986        7.491558
               1985        7.913945
               1984        7.689197
               1983        8.026440
               1982        7.438704
               1981        6.784000
               1980        6.153479
               1979        5.783516
               1978        5.635035
               1977        5.670138
               1976        5.767214
               1975        5.927298
               1974        6.133508
               1973        6.568496
               1972        7.056473
               1971        7.044025
China          2014        5.358338
               2013        5.306225
               2012        5.302652
               2011        5.205434
               2010        5.401937
               2009        5.573417
               2008        5.798459
               2007        6.156229
               2006        6.495481
               2005        6.819781
               2004        7.462184
               2003        7.611126
               2002        8.108541
               2001        8.563851
               2000        8.881148
               1999        9.813584
               1998        9.256623
               1997       11.471135
               1996       10.283800
               1995       12.216496
               1994       12.670941
               1993       14.310941
               1992       15.160175
               1991       16.898704
               1990       17.911886
               1989       18.052685
               1988       18.860396
               1987       18.922522
               1986       19.392149
               1985       20.021037
               1984       18.559930
               1983       18.872562
               1982       18.794264
               1981       18.891944
               1980       18.139023
               1979       19.026029
               1978       18.922859
               1977       19.983016
               1976       19.931858
               1975       20.465564
               1974       20.318703
               1973       20.831115
               1972       21.329853
               1971       21.596575
European Union 2014       15.459913
               2013       17.060117
               2012       16.344142
               2011       15.673458
               2010       17.275371
               2009       16.880886
               2008       16.024392
               2007       14.444750
               2006       16.485827
               2005       16.609216
               2004       16.525770
               2003       16.631710
               2002       16.253825
               2001       16.891597
               2000       16.064259
               1999       16.852581
               1998       16.842029
               1997       17.164758
               1996       17.994964
               1995       16.999967
               1994       16.963227
               1993      

## EDA and Data Prep

In [6]:
df_indicator.isnull().sum()

EN.CO2.BLDG.ZS    0
dtype: int64

In [7]:
# Make a dataset back-up
df_indicator_backup_1 = df_indicator.copy()

In [8]:
df_indicator = df_indicator.reset_index()

In [9]:
df_indicator.head(3)

,country,year,EN.CO2.BLDG.ZS
0,Brazil,2014,4.289736
1,Brazil,2013,4.508896
2,Brazil,2012,4.746116


In [10]:
df_indicator.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 352 entries, 0 to 351
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   country         352 non-null    object 
 1   year            352 non-null    int64  
 2   EN.CO2.BLDG.ZS  352 non-null    float64
dtypes: float64(1), int64(1), object(1)
memory usage: 8.4+ KB


In [11]:
df_indicator['year'] = df_indicator['year'].astype(int)
type(df_indicator['year'][0])

numpy.int64

In [12]:
df_indicator.head(3)

,country,year,EN.CO2.BLDG.ZS
0,Brazil,2014,4.289736
1,Brazil,2013,4.508896
2,Brazil,2012,4.746116


In [13]:
# Make year - date time into the index
df_indicator.set_index('year', inplace= True)
df_indicator.head()

,country,EN.CO2.BLDG.ZS
year,,
2014,Brazil,4.289736
2013,Brazil,4.508896
2012,Brazil,4.746116
2011,Brazil,5.159270
2010,Brazil,5.346396


In [14]:
# sort the values by year date time
df_indicator = df_indicator.sort_index()
df_indicator.head(10)

,country,EN.CO2.BLDG.ZS
year,,
1971,World,18.615556
1971,United States,19.061400
1971,United Kingdom,17.230274
1971,India,15.087564
1971,Brazil,7.044025
1971,South Africa,7.925393
1971,China,21.596575
1971,European Union,21.950546
1972,United Kingdom,18.141505


In [15]:
# Update column name
df_indicator.columns = ["country" ,"Indicator"]
df_indicator.head()

,country,Indicator
year,,
1971,World,18.615556
1971,United States,19.061400
1971,United Kingdom,17.230274
1971,India,15.087564
1971,Brazil,7.044025


In [16]:
df_indicator.head(10)

,country,Indicator
year,,
1971,World,18.615556
1971,United States,19.061400
1971,United Kingdom,17.230274
1971,India,15.087564
1971,Brazil,7.044025
1971,South Africa,7.925393
1971,China,21.596575
1971,European Union,21.950546
1972,United Kingdom,18.141505


In [17]:
df_indicator = pd.pivot_table(df_indicator, values='Indicator', 
                 columns='country', index='year')
df_indicator.head(10)

country,Brazil,China,European Union,India,South Africa,United Kingdom,United States,World
year,,,,,,,,
1971,7.044025,21.596575,21.950546,15.087564,7.925393,17.230274,19.061400,18.615556
1972,7.056473,21.329853,22.129084,14.035274,7.742371,18.141505,18.390586,18.432397
1973,6.568496,20.831115,21.894976,14.183907,6.949115,17.421817,17.048219,17.565715
1974,6.133508,20.318703,20.240601,12.503688,6.815974,18.435426,16.687413,16.947899
1975,5.927298,20.465564,20.728440,12.209276,6.572400,17.964301,17.031575,17.173455
1976,5.767214,19.931858,20.164812,12.336263,6.429296,17.870337,17.264680,17.137039
1977,5.670138,19.983016,19.668188,12.602554,5.527939,18.214177,16.128702,16.512286
1978,5.635035,18.922859,19.879768,13.587028,6.764253,17.977528,16.105992,16.480944
1979,5.783516,19.026029,19.616910,13.698245,6.058166,18.140961,14.846802,15.885459


In [18]:
regions

['BRA', 'IND', 'CHN', 'ZAF', 'USA', 'GBR', 'WLD', 'EUU']

In [19]:
df_indicator.columns

Index(['Brazil', 'China', 'European Union', 'India', 'South Africa',
       'United Kingdom', 'United States', 'World'],
      dtype='object', name='country')

In [20]:
# PAY ATTENTION HERE SO THAT YOU PUT THEM IN THE RIGHT ORDER ! 

df_indicator.columns = [regions[0], regions[2], regions[7], regions[1], regions[3], regions[5], regions[4], regions[6] ]

df_indicator.head()

,BRA,CHN,EUU,IND,ZAF,GBR,USA,WLD
year,,,,,,,,
1971,7.044025,21.596575,21.950546,15.087564,7.925393,17.230274,19.061400,18.615556
1972,7.056473,21.329853,22.129084,14.035274,7.742371,18.141505,18.390586,18.432397
1973,6.568496,20.831115,21.894976,14.183907,6.949115,17.421817,17.048219,17.565715
1974,6.133508,20.318703,20.240601,12.503688,6.815974,18.435426,16.687413,16.947899
1975,5.927298,20.465564,20.728440,12.209276,6.572400,17.964301,17.031575,17.173455


In [21]:
df_indicator.tail()

,BRA,CHN,EUU,IND,ZAF,GBR,USA,WLD
year,,,,,,,,
2010,5.346396,5.401937,17.275371,6.208523,3.412499,21.763386,10.190292,9.204829
2011,5.159270,5.205434,15.673458,6.173230,4.123685,19.065864,10.230125,8.805714
2012,4.746116,5.302652,16.344142,5.701490,5.553239,20.131135,9.712099,8.632350
2013,4.508896,5.306225,17.060117,5.704307,5.591515,20.827589,10.679440,8.804332
2014,4.289736,5.358338,15.459913,5.490006,5.469054,19.061397,11.011918,8.595320


In [22]:
df_indicator.to_excel('dfinc.xlsx')

## Adding polynomial features

In [25]:
degree=3
poly = PolynomialFeatures(degree=degree, include_bias=False)
poly

PolynomialFeatures(degree=3, include_bias=False)

In [27]:
df_indicator.head()

,BRA,CHN,EUU,IND,ZAF,GBR,USA,WLD
year,,,,,,,,
1971,7.044025,21.596575,21.950546,15.087564,7.925393,17.230274,19.061400,18.615556
1972,7.056473,21.329853,22.129084,14.035274,7.742371,18.141505,18.390586,18.432397
1973,6.568496,20.831115,21.894976,14.183907,6.949115,17.421817,17.048219,17.565715
1974,6.133508,20.318703,20.240601,12.503688,6.815974,18.435426,16.687413,16.947899
1975,5.927298,20.465564,20.728440,12.209276,6.572400,17.964301,17.031575,17.173455


In [28]:
df_indicator.index

Index([1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982,
       1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994,
       1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006,
       2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014],
      dtype='int64', name='year')

In [29]:
df_indicator.index.values

array([1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981,
       1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992,
       1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014])

In [32]:
# Year is the feature and convert to a 2D array
t = df_indicator.index.values.reshape(-1,1)
t

array([[1971],
       [1972],
       [1973],
       [1974],
       [1975],
       [1976],
       [1977],
       [1978],
       [1979],
       [1980],
       [1981],
       [1982],
       [1983],
       [1984],
       [1985],
       [1986],
       [1987],
       [1988],
       [1989],
       [1990],
       [1991],
       [1992],
       [1993],
       [1994],
       [1995],
       [1996],
       [1997],
       [1998],
       [1999],
       [2000],
       [2001],
       [2002],
       [2003],
       [2004],
       [2005],
       [2006],
       [2007],
       [2008],
       [2009],
       [2010],
       [2011],
       [2012],
       [2013],
       [2014]])

In [31]:
t.shape

(44, 1)

In [33]:
poly

PolynomialFeatures(degree=3, include_bias=False)

In [36]:
X = poly.fit_transform(t)
X

array([[1.97100000e+03, 3.88484100e+06, 7.65702161e+09],
       [1.97200000e+03, 3.88878400e+06, 7.66868205e+09],
       [1.97300000e+03, 3.89272900e+06, 7.68035432e+09],
       [1.97400000e+03, 3.89667600e+06, 7.69203842e+09],
       [1.97500000e+03, 3.90062500e+06, 7.70373438e+09],
       [1.97600000e+03, 3.90457600e+06, 7.71544218e+09],
       [1.97700000e+03, 3.90852900e+06, 7.72716183e+09],
       [1.97800000e+03, 3.91248400e+06, 7.73889335e+09],
       [1.97900000e+03, 3.91644100e+06, 7.75063674e+09],
       [1.98000000e+03, 3.92040000e+06, 7.76239200e+09],
       [1.98100000e+03, 3.92436100e+06, 7.77415914e+09],
       [1.98200000e+03, 3.92832400e+06, 7.78593817e+09],
       [1.98300000e+03, 3.93228900e+06, 7.79772909e+09],
       [1.98400000e+03, 3.93625600e+06, 7.80953190e+09],
       [1.98500000e+03, 3.94022500e+06, 7.82134662e+09],
       [1.98600000e+03, 3.94419600e+06, 7.83317326e+09],
       [1.98700000e+03, 3.94816900e+06, 7.84501180e+09],
       [1.98800000e+03, 3.95214

In [37]:
X.shape

(44, 3)

In [40]:
t_future=np.arange(2015,2051).reshape(-1,1)
t_future

array([[2015],
       [2016],
       [2017],
       [2018],
       [2019],
       [2020],
       [2021],
       [2022],
       [2023],
       [2024],
       [2025],
       [2026],
       [2027],
       [2028],
       [2029],
       [2030],
       [2031],
       [2032],
       [2033],
       [2034],
       [2035],
       [2036],
       [2037],
       [2038],
       [2039],
       [2040],
       [2041],
       [2042],
       [2043],
       [2044],
       [2045],
       [2046],
       [2047],
       [2048],
       [2049],
       [2050]])

In [41]:
X_future = poly.fit_transform(t_future)
X_future

array([[2.01500000e+03, 4.06022500e+06, 8.18135338e+09],
       [2.01600000e+03, 4.06425600e+06, 8.19354010e+09],
       [2.01700000e+03, 4.06828900e+06, 8.20573891e+09],
       [2.01800000e+03, 4.07232400e+06, 8.21794983e+09],
       [2.01900000e+03, 4.07636100e+06, 8.23017286e+09],
       [2.02000000e+03, 4.08040000e+06, 8.24240800e+09],
       [2.02100000e+03, 4.08444100e+06, 8.25465526e+09],
       [2.02200000e+03, 4.08848400e+06, 8.26691465e+09],
       [2.02300000e+03, 4.09252900e+06, 8.27918617e+09],
       [2.02400000e+03, 4.09657600e+06, 8.29146982e+09],
       [2.02500000e+03, 4.10062500e+06, 8.30376562e+09],
       [2.02600000e+03, 4.10467600e+06, 8.31607358e+09],
       [2.02700000e+03, 4.10872900e+06, 8.32839368e+09],
       [2.02800000e+03, 4.11278400e+06, 8.34072595e+09],
       [2.02900000e+03, 4.11684100e+06, 8.35307039e+09],
       [2.03000000e+03, 4.12090000e+06, 8.36542700e+09],
       [2.03100000e+03, 4.12496100e+06, 8.37779579e+09],
       [2.03200000e+03, 4.12902